### ISSUE TITLE
support templating for http sinks

### ISSUE THREAD

**Issue by haveiss** [goto/meteor#44]
**Is your feature request related to a problem? Please describe.**
The current implementation of HTTP sinks lacks the flexibility to dynamically configure URLs and payloads, making it challenging to seamlessly integrate with existing APIs without establishing a rigid contract with Meteor. For example patching existing resource in guardian.

**Describe the solution you'd like**
I propose introducing templating support for both the URL and payload in HTTP sinks. This enhancement would empower users to dynamically configure endpoints and customize payloads based on specific requirements.

```yaml
sinks:
  name: http
  config:
    method: PATCH
    success_code: 200
    url: https://example.com/v1beta1/{{.Urn}}
    headers:
      some-header: some-value
    script:
      engine: tengo
      source: |
        // global variable asset
        payload := {
          // do transformation here
          key1: asset.urn,
          ...
        }
        sink(payload)
```
